export type GenreSeed = {
  slug: string;
  name: string;
  categorySlug: string;
  summary: string;
  definition: string;
  dominantTypes: string[];
  register: string;
  length: string;
  difficulty: number;
  plan: { title: string; goal: string; share: number; prompts: string[] }[];
  method: string[];
  connectors: string[];
  phrases: string[];
  checklist: string[];
  pitfalls: string[];
  criteria: { label: string; weight: number }[];
  sample: string;
};

export const literaryGenres: GenreSeed[] = [
  {
    slug: "nouvelle",
    name: "La nouvelle",
    categorySlug: "litteraires",
    summary: "Récit bref à intrigue unique, tendu vers une chute.",
    definition:
      "La nouvelle est un récit court centré sur une seule intrigue, peu de personnages et une durée resserrée. Tout y est subordonné à l'effet final : la chute, qui relit rétrospectivement le texte entier. Contrairement au roman, elle commence in medias res et élimine tout ce qui n'est pas indispensable.",
    dominantTypes: ["narratif", "descriptif"],
    register: "littéraire",
    length: "1 000 à 5 000 mots",
    difficulty: 3,
    plan: [
      { title: "Ouverture in medias res", goal: "Entrer immédiatement dans la situation", share: 15, prompts: ["Quelle première phrase installe à la fois le lieu, le personnage et une tension ?", "Quel détail concret ancre la scène ?"] },
      { title: "Mise en place du nœud", goal: "Installer le manque ou le secret", share: 25, prompts: ["Que veut le personnage ? Qu'est-ce qui l'en empêche ?", "Quel indice discret prépare la chute ?"] },
      { title: "Montée de la tension", goal: "Resserrer l'étau par des péripéties brèves", share: 35, prompts: ["Quelles trois étapes aggravent la situation ?", "Où insérer un dialogue révélateur ?"] },
      { title: "Point de bascule", goal: "Le moment où tout se joue", share: 15, prompts: ["Quelle action ou révélation est irréversible ?"] },
      { title: "Chute", goal: "Clore en relançant le sens", share: 10, prompts: ["La dernière phrase relit-elle tout le récit autrement ?", "Peut-on la rendre plus brève ?"] },
    ],
    method: [
      "Écrire d'abord la chute : elle commande la sélection des détails.",
      "Limiter à deux ou trois personnages et un seul fil narratif.",
      "Choisir un point de vue (interne de préférence) et s'y tenir.",
      "Semer deux indices discrets qui ne prendront sens qu'à la fin.",
      "Couper tout ce qui ne sert ni la tension ni la chute.",
    ],
    connectors: ["Soudain", "Puis", "Quelques heures plus tard", "Alors", "C'est à ce moment que", "Enfin"],
    phrases: [
      "Il crut d'abord à une erreur.",
      "Rien, ce matin-là, ne laissait prévoir…",
      "Elle comprit, mais trop tard.",
      "Ce fut la dernière fois que…",
      "Quand il se retourna, la place était vide.",
    ],
    checklist: [
      "L'intrigue tient en une seule phrase.",
      "Le récit commence au plus près de la crise.",
      "Le point de vue est constant.",
      "Les temps du récit sont cohérents.",
      "La chute est préparée mais non annoncée.",
      "Aucun paragraphe n'est simplement décoratif.",
    ],
    pitfalls: ["Ouvrir par une longue exposition", "Multiplier les personnages secondaires", "Expliquer la chute après coup", "Abuser des adverbes dans les verbes de parole"],
    criteria: [
      { label: "Unité et resserrement de l'intrigue", weight: 30 },
      { label: "Efficacité de la chute", weight: 25 },
      { label: "Qualité du style et des images", weight: 25 },
      { label: "Cohérence narrative (temps, point de vue)", weight: 20 },
    ],
    sample:
      "Le train avait vingt minutes de retard, et c'est ce retard, exactement, qui lui sauva la vie. Il ne le sut que le lendemain, en dépliant le journal.",
  },
  {
    slug: "conte",
    name: "Le conte",
    categorySlug: "litteraires",
    summary: "Récit merveilleux à visée initiatique ou morale.",
    definition:
      "Le conte est un récit traditionnel situé dans un temps et un lieu indéterminés, où le merveilleux est accepté sans explication. Il suit un schéma actantiel stable (héros, quête, adjuvants, opposants) et délivre, explicitement ou non, un enseignement.",
    dominantTypes: ["narratif", "descriptif"],
    register: "littéraire",
    length: "800 à 2 500 mots",
    difficulty: 2,
    plan: [
      { title: "Formule d'ouverture", goal: "Installer l'indétermination merveilleuse", share: 10, prompts: ["« Il était une fois… » : quelle variante personnelle ?"] },
      { title: "Situation initiale", goal: "Présenter le héros et son manque", share: 15, prompts: ["Quel manque initial ? (objet, parent, statut)"] },
      { title: "Départ et épreuves", goal: "Trois épreuves graduées", share: 40, prompts: ["Quelles sont les trois épreuves ?", "Quel adjuvant magique intervient ?"] },
      { title: "Épreuve décisive", goal: "Affronter l'opposant", share: 20, prompts: ["Comment le héros triomphe-t-il par une qualité morale ?"] },
      { title: "Réparation et formule finale", goal: "Combler le manque et conclure", share: 15, prompts: ["Quelle récompense ?", "Quelle morale implicite ?"] },
    ],
    method: [
      "Poser un manque clair dès la situation initiale.",
      "Respecter la règle de trois (trois épreuves, trois objets, trois frères).",
      "Donner un objet magique dont l'usage est limité par une règle.",
      "Faire triompher une qualité (ruse, générosité, patience) plutôt que la force.",
      "Clore par le retour à l'ordre et une formule rituelle.",
    ],
    connectors: ["Il était une fois", "Or", "Le lendemain", "Après avoir longtemps marché", "Alors", "Depuis ce jour"],
    phrases: [
      "Dans un royaume dont nul ne connaissait les frontières…",
      "Prends ceci, mais ne t'en sers qu'une seule fois.",
      "Trois jours et trois nuits il marcha.",
      "Et depuis ce jour, au village, on raconte que…",
    ],
    checklist: [
      "Le cadre spatio-temporel reste indéterminé.",
      "Le manque initial est explicite.",
      "Les épreuves sont graduées.",
      "L'objet magique a une règle d'usage.",
      "Le dénouement répare le manque.",
      "Le passé simple et l'imparfait alternent correctement.",
    ],
    pitfalls: ["Introduire des références contemporaines précises", "Expliquer rationnellement le merveilleux", "Moraliser lourdement", "Oublier la gradation des épreuves"],
    criteria: [
      { label: "Respect du schéma du conte", weight: 30 },
      { label: "Imaginaire et cohérence du merveilleux", weight: 25 },
      { label: "Langue et temps du récit", weight: 25 },
      { label: "Portée morale", weight: 20 },
    ],
    sample:
      "Il était une fois, au bord d'un fleuve qui changeait de nom chaque saison, une fillette qui savait écouter les pierres. Son unique richesse était un dé de cuivre que lui avait laissé sa grand-mère, avec cette consigne : « Tu ne le feras tourner que trois fois. »",
  },
  {
    slug: "fable",
    name: "La fable",
    categorySlug: "litteraires",
    summary: "Court récit allégorique, souvent animalier, fermé par une morale.",
    definition:
      "La fable associe un récit bref et plaisant (le corps) à un enseignement (l'âme). Les personnages, souvent animaux, incarnent des types humains. Le vers, le dialogue et la vivacité du rythme y servent une leçon politique ou morale, parfois ironique.",
    dominantTypes: ["narratif", "argumentatif"],
    register: "littéraire",
    length: "15 à 40 vers ou 200 à 400 mots",
    difficulty: 3,
    plan: [
      { title: "Exposition rapide", goal: "Poser les deux personnages typés", share: 20, prompts: ["Quel vice et quelle qualité s'affrontent ?"] },
      { title: "Dialogue ou confrontation", goal: "Faire vivre l'opposition", share: 40, prompts: ["Que dit chacun ? En combien de répliques ?"] },
      { title: "Renversement", goal: "Faire triompher l'inattendu", share: 20, prompts: ["Qui est pris à son propre jeu ?"] },
      { title: "Morale", goal: "Dégager la leçon", share: 20, prompts: ["Morale explicite en tête, en fin, ou implicite ?"] },
    ],
    method: [
      "Choisir deux figures contrastées et un vice unique à critiquer.",
      "Resserrer le récit : une situation, un dialogue, un retournement.",
      "Varier le rythme (phrases brèves pour l'action, longues pour la pose).",
      "Formuler la morale en une sentence mémorable et rythmée.",
    ],
    connectors: ["Un jour", "Aussitôt", "Mais", "Cependant", "Ainsi", "Apprenez que"],
    phrases: [
      "Maître Renard, par l'odeur alléché…",
      "Il n'en fallut pas davantage.",
      "Tel est pris qui croyait prendre.",
      "Apprenez que tout flatteur vit aux dépens de celui qui l'écoute.",
    ],
    checklist: [
      "Les personnages sont des types reconnaissables.",
      "Le récit tient en une scène.",
      "Le dialogue est vif et caractérisant.",
      "La morale découle réellement du récit.",
      "Le rythme est travaillé.",
    ],
    pitfalls: ["Morale sans rapport avec l'histoire", "Récit trop long pour la leçon", "Personnages interchangeables", "Leçon déjà donnée dans l'exposition"],
    criteria: [
      { label: "Pertinence de l'allégorie", weight: 30 },
      { label: "Vivacité du récit et du dialogue", weight: 25 },
      { label: "Qualité de la morale", weight: 25 },
      { label: "Travail du rythme et de la langue", weight: 20 },
    ],
    sample:
      "Un Chat savant, nommé professeur par les souris elles-mêmes, leur enseignait l'art de n'avoir plus peur. Les leçons furent brèves : il n'eut bientôt plus d'élèves.",
  },
  {
    slug: "autobiographie",
    name: "Le récit autobiographique",
    categorySlug: "litteraires",
    summary: "Récit rétrospectif de sa propre existence, fondé sur le pacte de sincérité.",
    definition:
      "L'autobiographie est le récit rétrospectif qu'une personne réelle fait de sa propre existence, lorsqu'elle met l'accent sur sa vie individuelle. Identité de l'auteur, du narrateur et du personnage : c'est le pacte autobiographique. Le texte joue de la double énonciation entre le « je » narrant (adulte qui se souvient) et le « je » narré (celui qui a vécu).",
    dominantTypes: ["narratif", "descriptif", "expressif"],
    register: "littéraire",
    length: "1 000 à 4 000 mots (extrait)",
    difficulty: 3,
    plan: [
      { title: "Pacte et cadrage", goal: "Annoncer le projet et la posture", share: 15, prompts: ["Pourquoi écrire ce souvenir aujourd'hui ?"] },
      { title: "Scène de souvenir", goal: "Restituer un moment précis et sensoriel", share: 35, prompts: ["Quels détails concrets (odeurs, sons, objets) ?"] },
      { title: "Regard rétrospectif", goal: "Faire parler le « je » adulte", share: 25, prompts: ["Que sais-je aujourd'hui que j'ignorais alors ?"] },
      { title: "Interprétation", goal: "Dégager le sens de l'épisode", share: 15, prompts: ["En quoi cet épisode m'a-t-il construit ?"] },
      { title: "Clôture", goal: "Relier passé et présent", share: 10, prompts: ["Quelle image ferme la boucle ?"] },
    ],
    method: [
      "Choisir un épisode unique et bref plutôt qu'un récit de vie complet.",
      "Alterner récit au passé et commentaires au présent.",
      "Travailler la mémoire sensorielle : un objet, une odeur, un son.",
      "Assumer les incertitudes de la mémoire (« il me semble que »).",
      "Éviter la justification : montrer plutôt que plaider.",
    ],
    connectors: ["À cette époque", "Je me souviens que", "Aujourd'hui encore", "Avec le recul", "Longtemps après", "C'est alors que"],
    phrases: [
      "Je me souviens surtout de…",
      "J'avais alors dix ans et je croyais que…",
      "Il me semble, mais la mémoire arrange les choses, que…",
      "Je n'ai compris que bien plus tard pourquoi…",
    ],
    checklist: [
      "Le pacte autobiographique est lisible.",
      "Le « je » narrant et le « je » narré sont distingués.",
      "Un épisode précis structure le texte.",
      "Les détails sensoriels sont concrets.",
      "Le texte dépasse l'anecdote par une interprétation.",
    ],
    pitfalls: ["Résumer toute une vie en quelques lignes", "Tomber dans le règlement de comptes", "Généraliser au « on »", "Multiplier les émotions nommées sans scène"],
    criteria: [
      { label: "Authenticité et précision du souvenir", weight: 30 },
      { label: "Maîtrise de la double énonciation", weight: 25 },
      { label: "Qualité de l'écriture", weight: 25 },
      { label: "Portée réflexive", weight: 20 },
    ],
    sample:
      "La cuisine sentait le pain grillé et l'eau de Javel. J'avais huit ans, et je croyais que les adultes ne pleuraient pas. Avec le recul, je sais que ma mère ce matin-là ne découpait pas les oignons.",
  },
  {
    slug: "poeme-lyrique",
    name: "Le poème lyrique",
    categorySlug: "litteraires",
    summary: "Expression travaillée d'un sentiment par le rythme et l'image.",
    definition:
      "Le poème lyrique dit le sujet et son émotion à travers une forme contrainte ou libre. Sa matière est double : le son (mètre, rime, assonance, allitération) et l'image (métaphore, comparaison, symbole). Le sens y naît autant du rythme que du lexique.",
    dominantTypes: ["expressif", "descriptif"],
    register: "littéraire",
    length: "12 à 40 vers",
    difficulty: 4,
    plan: [
      { title: "Motif initial", goal: "Poser l'image ou la scène déclenchante", share: 25, prompts: ["Quelle image concrète ouvre le poème ?"] },
      { title: "Développement", goal: "Filer l'image, varier les sensations", share: 35, prompts: ["Quelle métaphore filée ?", "Quels échos sonores ?"] },
      { title: "Tension / rupture", goal: "Introduire un contre-mouvement", share: 20, prompts: ["Où le poème change-t-il de direction ?"] },
      { title: "Chute poétique", goal: "Clore par une formule dense", share: 20, prompts: ["Le dernier vers est-il mémorable et bref ?"] },
    ],
    method: [
      "Partir d'une image concrète, jamais d'une idée abstraite.",
      "Choisir une contrainte (mètre, strophe, refrain) et l'assumer.",
      "Travailler les sonorités : lire à voix haute et compter les syllabes.",
      "Supprimer un mot sur cinq à la relecture : la densité fait le poème.",
      "Éviter les rimes attendues (amour/toujours, cœur/bonheur).",
    ],
    connectors: ["Et", "Comme", "Ainsi que", "Pourtant", "Ô", "Jusqu'à ce que"],
    phrases: [
      "Il y a dans ce soir quelque chose de…",
      "Comme un oiseau qui aurait oublié le ciel…",
      "Je ne sais plus si c'est la nuit qui tombe ou moi.",
      "Reste. Le reste attendra.",
    ],
    checklist: [
      "Le poème repose sur une image centrale.",
      "Le rythme a été vérifié à voix haute.",
      "Les sonorités sont travaillées (allitérations, assonances).",
      "Aucun cliché ne subsiste.",
      "La chute est brève et forte.",
    ],
    pitfalls: ["Prose découpée en vers", "Accumulation d'abstractions", "Rimes pauvres et attendues", "Ponctuation expressive remplaçant l'image"],
    criteria: [
      { label: "Force et cohérence des images", weight: 30 },
      { label: "Travail du rythme et des sonorités", weight: 30 },
      { label: "Originalité", weight: 20 },
      { label: "Unité du poème", weight: 20 },
    ],
    sample:
      "Le quai se vide comme une phrase qu'on abandonne. / Reste la lampe, obstinée, / qui compte les absents un par un.",
  },
  {
    slug: "scene-de-theatre",
    name: "La scène de théâtre",
    categorySlug: "litteraires",
    summary: "Texte dialogué avec didascalies, construit sur un conflit.",
    definition:
      "La scène théâtrale repose sur la double énonciation : les personnages se parlent, mais l'auteur parle au spectateur. Elle est faite de répliques et de didascalies, et progresse par un conflit : chaque personnage veut quelque chose que l'autre lui refuse.",
    dominantTypes: ["narratif", "argumentatif", "expressif"],
    register: "littéraire",
    length: "400 à 1 200 mots",
    difficulty: 3,
    plan: [
      { title: "Didascalie initiale", goal: "Poser le décor, l'époque, les présences", share: 10, prompts: ["Où sommes-nous ? Qui est déjà en scène ?"] },
      { title: "Ouverture du conflit", goal: "Faire apparaître l'enjeu dès les premières répliques", share: 25, prompts: ["Que veut chaque personnage ?"] },
      { title: "Affrontement", goal: "Faire monter la tension (stichomythie, tirade)", share: 40, prompts: ["Où placer une tirade ? Où accélérer ?"] },
      { title: "Coup de théâtre ou sortie", goal: "Renverser la situation", share: 25, prompts: ["Quelle réplique finale laisse le spectateur en suspens ?"] },
    ],
    method: [
      "Donner à chaque personnage un objectif inconciliable avec celui de l'autre.",
      "Caractériser par la parole : niveau de langue, tics, longueur des répliques.",
      "Limiter les didascalies à ce qui est jouable.",
      "Alterner répliques longues et stichomythies pour varier le rythme.",
      "Terminer sur une réplique qui relance l'action.",
    ],
    connectors: ["Alors", "Mais enfin", "Soit", "Puisque", "En ce cas", "Un instant"],
    phrases: [
      "(Un temps.)",
      "Vous êtes venu pour cela, n'est-ce pas ?",
      "Je ne vous demande pas votre avis, je vous demande votre signature.",
      "(Elle sort sans refermer la porte.)",
    ],
    checklist: [
      "Le conflit est perceptible dès le début.",
      "Les répliques sont attribuées clairement.",
      "Les didascalies sont jouables et concises.",
      "Le niveau de langue distingue les personnages.",
      "La fin de scène relance l'intérêt.",
    ],
    pitfalls: ["Répliques narratives qui racontent au lieu de jouer", "Didascalies littéraires injouables", "Personnages au discours interchangeable", "Absence de conflit"],
    criteria: [
      { label: "Efficacité dramatique du conflit", weight: 30 },
      { label: "Qualité du dialogue", weight: 30 },
      { label: "Usage des didascalies", weight: 20 },
      { label: "Caractérisation des personnages", weight: 20 },
    ],
    sample:
      "LA DIRECTRICE, sans lever les yeux. — Asseyez-vous. / KARIM. — Je préfère rester debout. / LA DIRECTRICE. — C'est précisément votre problème. (Un temps.) Vous préférez toujours.",
  },
  {
    slug: "plaidoyer",
    name: "Le plaidoyer / le pamphlet",
    categorySlug: "litteraires",
    summary: "Écrit d'idées engagé qui défend (plaidoyer) ou attaque (pamphlet).",
    definition:
      "Le plaidoyer défend une cause, une personne ou une valeur ; le réquisitoire et le pamphlet attaquent. Tous reposent sur une argumentation assumée, un style oratoire (apostrophes, questions rhétoriques, gradations) et une implication explicite de l'énonciateur.",
    dominantTypes: ["argumentatif", "expressif"],
    register: "soutenu",
    length: "600 à 1 500 mots",
    difficulty: 3,
    plan: [
      { title: "Exorde", goal: "Capter l'auditoire et poser la cause", share: 15, prompts: ["Quelle image ou quel fait choquant pour ouvrir ?"] },
      { title: "Exposé des faits", goal: "Établir la situation à défendre", share: 20, prompts: ["Quels faits incontestables ?"] },
      { title: "Argumentation", goal: "Trois arguments gradués", share: 35, prompts: ["Argument juridique, moral, humain ?"] },
      { title: "Réfutation", goal: "Démonter la thèse adverse", share: 15, prompts: ["Quelle objection majeure anticiper ?"] },
      { title: "Péroraison", goal: "Emporter l'adhésion", share: 15, prompts: ["Quel appel final à l'action ?"] },
    ],
    method: [
      "Nommer dès l'exorde la cause défendue et l'adversaire combattu.",
      "Graduer les arguments du plus technique au plus humain.",
      "Alterner raison (logos) et émotion (pathos) sans céder à l'invective.",
      "Travailler les rythmes ternaires et les anaphores.",
      "Terminer par une injonction ou une formule frappante.",
    ],
    connectors: ["Non seulement… mais encore", "Certes… mais", "Dès lors", "Comment accepter que", "En vérité", "Pour toutes ces raisons"],
    phrases: [
      "On nous répète que… Je prétends le contraire.",
      "Faut-il rappeler que…?",
      "Je ne demande pas la pitié : je demande la justice.",
      "Il ne s'agit pas d'une opinion, il s'agit d'un fait.",
    ],
    checklist: [
      "La cause est nommée dès l'ouverture.",
      "Chaque argument est illustré par un fait.",
      "La thèse adverse est réfutée loyalement.",
      "Les procédés oratoires sont dosés.",
      "La péroraison appelle une action.",
    ],
    pitfalls: ["Attaquer la personne plutôt que la thèse", "Émotion non soutenue par des faits", "Accumulation d'exclamations", "Absence de réfutation"],
    criteria: [
      { label: "Force de l'argumentation", weight: 35 },
      { label: "Maîtrise des procédés oratoires", weight: 25 },
      { label: "Structure rhétorique", weight: 20 },
      { label: "Qualité de la langue", weight: 20 },
    ],
    sample:
      "On nous dit que ces élèves sont « hors parcours ». Hors de quel parcours ? Celui qu'on a tracé sans eux, puis refermé derrière eux. Je ne plaide pas l'indulgence : je plaide la cohérence.",
  },
];

export const journalisticGenres: GenreSeed[] = [
  {
    slug: "breve",
    name: "La brève",
    categorySlug: "journalistiques",
    summary: "Information factuelle condensée répondant aux 5 W.",
    definition:
      "La brève livre une information en quelques lignes, sans titre parfois, toujours sans commentaire. Elle répond aux questions essentielles — qui, quoi, où, quand, pourquoi/comment — en suivant la loi de la pyramide inversée : l'essentiel d'abord.",
    dominantTypes: ["explicatif", "narratif"],
    register: "courant",
    length: "60 à 150 mots",
    difficulty: 1,
    plan: [
      { title: "Attaque", goal: "L'information principale en une phrase", share: 40, prompts: ["Quoi ? Qui ? Où ? Quand ?"] },
      { title: "Précisions", goal: "Chiffres, circonstances, source", share: 40, prompts: ["Quelles données vérifiées ajouter ?"] },
      { title: "Suite", goal: "Ce qui va se passer ensuite", share: 20, prompts: ["Quelle échéance, quelle enquête en cours ?"] },
    ],
    method: [
      "Hiérarchiser : la phrase 1 doit suffire si le lecteur s'arrête là.",
      "Vérifier et citer la source de chaque chiffre.",
      "Bannir tout adjectif évaluatif.",
      "Phrases courtes, voix active, verbes précis.",
    ],
    connectors: ["Selon", "D'après", "Par ailleurs", "Au total", "À ce jour", "Dans les prochains jours"],
    phrases: [
      "Selon un communiqué publié mardi, …",
      "L'incident n'a fait aucun blessé.",
      "Une enquête a été ouverte.",
      "Le bilan s'élève à…",
    ],
    checklist: [
      "Les 5 W sont présents.",
      "L'information essentielle est en tête.",
      "Aucune opinion n'apparaît.",
      "Les sources sont mentionnées.",
      "Le texte ne dépasse pas la longueur visée.",
    ],
    pitfalls: ["Commencer par le contexte", "Employer des adjectifs subjectifs", "Omettre la date ou le lieu", "Donner un chiffre sans source"],
    criteria: [
      { label: "Complétude informative (5 W)", weight: 35 },
      { label: "Hiérarchisation", weight: 25 },
      { label: "Neutralité", weight: 20 },
      { label: "Concision et correction", weight: 20 },
    ],
    sample:
      "Un incendie s'est déclaré mardi en fin de journée dans un entrepôt de la zone industrielle de Sidi Maârouf, à Casablanca. Selon la protection civile, le feu a été maîtrisé en deux heures et n'a fait aucune victime. Une enquête a été ouverte pour en déterminer l'origine.",
  },
  {
    slug: "reportage",
    name: "Le reportage",
    categorySlug: "journalistiques",
    summary: "Récit de terrain qui fait voir une réalité par le témoignage.",
    definition:
      "Le reportage raconte ce que le journaliste a vu et entendu sur le terrain. Il combine narration, description et citations pour faire éprouver une situation au lecteur. Son autorité vient de la présence : scènes concrètes, détails vérifiés, voix rapportées.",
    dominantTypes: ["narratif", "descriptif", "explicatif"],
    register: "courant",
    length: "800 à 2 000 mots",
    difficulty: 3,
    plan: [
      { title: "Scène d'ouverture", goal: "Plonger le lecteur dans un moment concret", share: 20, prompts: ["Quelle scène vue sur place ouvre le texte ?"] },
      { title: "Nœud informatif (nut graph)", goal: "Expliquer de quoi il s'agit et pourquoi c'est important", share: 15, prompts: ["Quelle est l'information centrale ?"] },
      { title: "Développement par séquences", goal: "Alterner scènes, témoignages et données", share: 45, prompts: ["Quelles trois séquences ?", "Quelles citations fortes ?"] },
      { title: "Mise en perspective", goal: "Contexte, chiffres, analyse d'expert", share: 10, prompts: ["Quel recul chiffré ou historique ?"] },
      { title: "Clôture (chute)", goal: "Revenir au terrain sur une image", share: 10, prompts: ["Quelle dernière image ou citation ?"] },
    ],
    method: [
      "Noter sur place les détails sensoriels : bruits, odeurs, gestes.",
      "Citer au style direct, avec le nom, l'âge et la fonction de la personne.",
      "Alterner plan large (données) et gros plan (personnes).",
      "Ne jamais inventer ni recomposer une scène.",
      "Se retirer du texte : le « je » reste discret.",
    ],
    connectors: ["Ce matin-là", "Un peu plus loin", "Dans le même temps", "Pourtant", "De fait", "Quelques heures plus tard"],
    phrases: [
      "Il est sept heures et la file s'allonge déjà.",
      "« On fait avec », souffle-t-il en haussant les épaules.",
      "Derrière lui, le chantier n'a pas avancé depuis mars.",
      "Les chiffres confirment l'impression : …",
    ],
    checklist: [
      "Le texte ouvre sur une scène concrète.",
      "Les témoins sont identifiés.",
      "Les citations sont fidèles.",
      "Les faits sont distingués des impressions.",
      "Le contexte chiffré est présent.",
    ],
    pitfalls: ["Reportage sans scène ni voix", "Citations décoratives", "Généralisations abusives", "Pathos substitué à l'enquête"],
    criteria: [
      { label: "Qualité de l'observation de terrain", weight: 30 },
      { label: "Construction en séquences", weight: 25 },
      { label: "Usage des témoignages", weight: 25 },
      { label: "Rigueur factuelle", weight: 20 },
    ],
    sample:
      "À six heures, la halle sent déjà la glace fondue et le gasoil. Rachid, 54 ans, pousse sa caisse vide le long du quai : « Avant, on vendait tout avant midi. Aujourd'hui, on attend. » Derrière lui, trois étals sur dix sont restés fermés.",
  },
  {
    slug: "interview",
    name: "L'interview",
    categorySlug: "journalistiques",
    summary: "Entretien rédigé en questions-réponses, précédé d'un chapô.",
    definition:
      "L'interview restitue la parole d'un interlocuteur sous forme de questions et de réponses. Elle suppose une préparation documentaire, des questions ouvertes, des relances, et un travail d'édition qui conserve la parole sans la trahir.",
    dominantTypes: ["explicatif", "argumentatif"],
    register: "courant",
    length: "600 à 1 500 mots",
    difficulty: 2,
    plan: [
      { title: "Chapô", goal: "Présenter l'invité et l'enjeu", share: 15, prompts: ["Qui est-il ? Pourquoi maintenant ?"] },
      { title: "Questions d'ouverture", goal: "Mettre en confiance, poser le cadre", share: 20, prompts: ["Quelle première question large ?"] },
      { title: "Cœur de l'entretien", goal: "Creuser, relancer, confronter", share: 45, prompts: ["Quelles trois questions difficiles ?", "Quelles relances prévoir ?"] },
      { title: "Question de clôture", goal: "Ouvrir sur l'avenir", share: 20, prompts: ["Quelle projection demander ?"] },
    ],
    method: [
      "Se documenter pour pouvoir contredire, pas seulement écouter.",
      "Préférer les questions ouvertes (« comment », « pourquoi »).",
      "Une idée par question, formulée en une phrase.",
      "Relancer sur les silences et les réponses vagues.",
      "Éditer pour la clarté sans modifier le sens des propos.",
    ],
    connectors: ["Vous dites que", "Justement", "Concrètement", "Pourtant", "Autrement dit", "Pour finir"],
    phrases: [
      "Vous affirmez que… Sur quoi vous fondez-vous ?",
      "Concrètement, qu'est-ce que cela change pour l'usager ?",
      "Certains vous reprochent… Que leur répondez-vous ?",
      "Où en serez-vous dans cinq ans ?",
    ],
    checklist: [
      "Le chapô situe l'invité et l'actualité.",
      "Les questions sont ouvertes et brèves.",
      "Les réponses vagues sont relancées.",
      "Les propos sont fidèlement restitués.",
      "La dernière question ouvre une perspective.",
    ],
    pitfalls: ["Questions fermées en série", "Questions plus longues que les réponses", "Absence de contradiction", "Réécriture excessive des réponses"],
    criteria: [
      { label: "Pertinence des questions", weight: 30 },
      { label: "Qualité des relances", weight: 25 },
      { label: "Fidélité et clarté", weight: 25 },
      { label: "Construction d'ensemble", weight: 20 },
    ],
    sample:
      "— Vous parlez de « crise du lire ». Les chiffres de l'édition sont pourtant stables. / — Stables en volume, oui. Mais regardez qui achète : ce sont les mêmes lecteurs, plus vieux de dix ans.",
  },
  {
    slug: "editorial",
    name: "L'éditorial",
    categorySlug: "journalistiques",
    summary: "Prise de position argumentée engageant la rédaction.",
    definition:
      "L'éditorial exprime la position d'un journal sur un fait d'actualité. Bref, construit, écrit dans un style net, il part d'un fait, formule un jugement, l'argumente et conclut par une injonction ou une mise en garde.",
    dominantTypes: ["argumentatif", "explicatif"],
    register: "soutenu",
    length: "350 à 700 mots",
    difficulty: 3,
    plan: [
      { title: "Fait déclencheur", goal: "Partir d'une actualité datée", share: 20, prompts: ["Quel événement précis justifie cet édito ?"] },
      { title: "Thèse", goal: "Énoncer le jugement du journal", share: 15, prompts: ["Quelle position en une phrase ?"] },
      { title: "Arguments", goal: "Deux ou trois raisons appuyées", share: 40, prompts: ["Quels faits soutiennent la thèse ?"] },
      { title: "Objection traitée", goal: "Montrer qu'on a pesé le contraire", share: 10, prompts: ["Quelle objection sérieuse reconnaître ?"] },
      { title: "Chute", goal: "Formule mémorable ou appel", share: 15, prompts: ["Quelle dernière phrase frappe ?"] },
    ],
    method: [
      "Ancrer dans un fait daté : l'édito n'est pas un essai.",
      "Formuler la thèse avant le troisième paragraphe.",
      "Une idée par paragraphe, phrases courtes.",
      "Éviter l'ironie facile : l'autorité vient de la rigueur.",
      "Soigner la dernière phrase autant que la première.",
    ],
    connectors: ["Or", "Dès lors", "Certes", "Il reste que", "En réalité", "Au fond"],
    phrases: [
      "La décision annoncée hier laisse perplexe.",
      "Il y a là plus qu'une maladresse : un choix.",
      "On objectera que… L'argument ne tient pas.",
      "Reste à savoir qui paiera ce retard.",
    ],
    checklist: [
      "Le fait déclencheur est daté et précis.",
      "La thèse est explicite.",
      "Chaque paragraphe porte une idée.",
      "L'objection principale est traitée.",
      "La chute est travaillée.",
    ],
    pitfalls: ["Commentaire sans fait", "Thèse noyée", "Invective", "Longueur excessive"],
    criteria: [
      { label: "Clarté et tenue de la thèse", weight: 30 },
      { label: "Solidité des arguments", weight: 30 },
      { label: "Ancrage dans l'actualité", weight: 20 },
      { label: "Style et concision", weight: 20 },
    ],
    sample:
      "Repousser encore la réforme des transports scolaires n'est pas une pause : c'est une décision. Celle de faire porter aux familles, un an de plus, le coût d'une organisation que l'on sait défaillante depuis 2019.",
  },
  {
    slug: "chronique",
    name: "La chronique",
    categorySlug: "journalistiques",
    summary: "Texte d'auteur régulier, au ton personnel et à l'angle affirmé.",
    definition:
      "La chronique est un billet signé, périodique, où la subjectivité est assumée. Elle part souvent d'un détail du quotidien pour atteindre une question générale. Son principal atout est la voix : rythme, humour, images reconnaissables.",
    dominantTypes: ["argumentatif", "expressif", "narratif"],
    register: "courant",
    length: "400 à 900 mots",
    difficulty: 3,
    plan: [
      { title: "Anecdote d'entrée", goal: "Un détail concret et vivant", share: 30, prompts: ["Quelle scène minuscule mais parlante ?"] },
      { title: "Bascule", goal: "Passer du détail à l'idée", share: 20, prompts: ["Comment élargir sans sermonner ?"] },
      { title: "Développement", goal: "Dérouler le propos avec exemples", share: 35, prompts: ["Quels deux exemples appuient l'idée ?"] },
      { title: "Chute", goal: "Revenir à l'anecdote, boucler", share: 15, prompts: ["Peut-on refermer sur l'image du début ?"] },
    ],
    method: [
      "Choisir un angle étroit : un objet, une phrase entendue, une habitude.",
      "Assumer le « je » sans occuper tout l'espace.",
      "Varier les longueurs de phrases pour créer un rythme.",
      "Préférer l'ironie à l'indignation.",
      "Boucler sur l'image initiale.",
    ],
    connectors: ["L'autre jour", "Bref", "Et pourtant", "Au fond", "Depuis", "Finalement"],
    phrases: [
      "L'autre matin, dans la file d'attente, …",
      "On rit, bien sûr. Puis on y repense.",
      "Rien de grave. Juste un symptôme.",
      "J'y suis retourné hier : la file était la même.",
    ],
    checklist: [
      "L'angle est étroit et identifiable.",
      "Le ton est constant.",
      "Le texte dépasse l'anecdote.",
      "Le rythme des phrases est varié.",
      "La chute boucle le texte.",
    ],
    pitfalls: ["Moraliser", "Accumuler les digressions", "Humour forcé", "Absence d'idée derrière l'anecdote"],
    criteria: [
      { label: "Singularité de la voix", weight: 30 },
      { label: "Qualité de l'angle", weight: 25 },
      { label: "Construction et chute", weight: 25 },
      { label: "Langue et rythme", weight: 20 },
    ],
    sample:
      "L'autre jour, un distributeur de billets m'a souhaité une excellente journée. Il n'avait plus de billets. C'est à peu près l'état du service public : les formules de politesse fonctionnent parfaitement.",
  },
  {
    slug: "critique",
    name: "La critique (littéraire, cinéma, spectacle)",
    categorySlug: "journalistiques",
    summary: "Compte rendu évaluatif d'une œuvre, informé et argumenté.",
    definition:
      "La critique informe sur une œuvre, l'analyse et porte un jugement motivé. Elle suppose une description loyale (sans tout dévoiler), une analyse des procédés et une évaluation argumentée, adressée à un lecteur qui n'a pas encore vu ou lu l'œuvre.",
    dominantTypes: ["explicatif", "argumentatif", "descriptif"],
    register: "soutenu",
    length: "500 à 1 200 mots",
    difficulty: 3,
    plan: [
      { title: "Accroche et identification", goal: "Titre, auteur, éditeur/réalisateur, date", share: 15, prompts: ["Quelle phrase donne envie de lire la suite ?"] },
      { title: "Présentation de l'œuvre", goal: "Résumé sans divulgâcher", share: 25, prompts: ["Que peut-on raconter sans gâcher ?"] },
      { title: "Analyse", goal: "Étudier deux ou trois procédés majeurs", share: 35, prompts: ["Écriture ? Mise en scène ? Structure ?"] },
      { title: "Jugement argumenté", goal: "Dire ce qui réussit et ce qui échoue", share: 15, prompts: ["Quelles réserves honnêtes ?"] },
      { title: "Recommandation", goal: "À qui s'adresse l'œuvre", share: 10, prompts: ["Pour quel public ?"] },
    ],
    method: [
      "Séparer nettement description, analyse et jugement.",
      "Appuyer chaque jugement sur un élément précis de l'œuvre.",
      "Citer brièvement (une phrase, un plan, une réplique).",
      "Situer l'œuvre dans un ensemble (genre, corpus, filmographie).",
      "Assumer une réserve : une critique sans nuance n'est pas crédible.",
    ],
    connectors: ["Dès les premières pages", "En revanche", "On regrettera", "Reste que", "À l'inverse", "Au total"],
    phrases: [
      "Le roman s'ouvre sur…",
      "Là où l'auteur excelle, c'est dans…",
      "On regrettera un dernier tiers plus convenu.",
      "À réserver aux lecteurs qui…",
    ],
    checklist: [
      "Les références de l'œuvre sont complètes.",
      "Le résumé ne divulgâche pas.",
      "Chaque jugement est justifié par un exemple.",
      "Les réserves sont formulées.",
      "Le public visé est indiqué.",
    ],
    pitfalls: ["Résumer toute l'intrigue", "Juger sans preuve", "Parler de soi plutôt que de l'œuvre", "Éloge ou démolition sans nuance"],
    criteria: [
      { label: "Qualité de l'analyse", weight: 35 },
      { label: "Justification du jugement", weight: 25 },
      { label: "Information sur l'œuvre", weight: 20 },
      { label: "Style", weight: 20 },
    ],
    sample:
      "Dès les premières pages, le roman impose son rythme : des phrases brèves, presque haletantes, qui miment la fuite du narrateur. L'effet est saisissant sur cent pages ; il s'épuise sur trois cents.",
  },
];
