import type { GenreSeed } from "./genres-literary";

export const professionalGenres: GenreSeed[] = [
  {
    slug: "lettre-administrative",
    name: "La lettre administrative",
    categorySlug: "professionnels",
    summary: "Courrier formel normalisé adressé à une autorité ou une institution.",
    definition:
      "La lettre administrative obéit à une mise en page normalisée (expéditeur, destinataire, lieu et date, objet, références, formule d'appel, corps, formule de politesse, signature). Elle est rédigée dans un style sobre, impersonnel et courtois, et traite d'un seul objet.",
    dominantTypes: ["argumentatif", "explicatif", "injonctif"],
    register: "soutenu",
    length: "200 à 450 mots",
    difficulty: 2,
    plan: [
      { title: "En-tête et objet", goal: "Identifier les parties et l'objet", share: 15, prompts: ["Objet en 6 mots maximum ?", "Références du dossier ?"] },
      { title: "Exposé de la situation", goal: "Rappeler les faits utiles", share: 30, prompts: ["Quels faits, quelles dates, quelles pièces ?"] },
      { title: "Demande ou argumentation", goal: "Formuler précisément la requête", share: 35, prompts: ["Que demandez-vous exactement ?", "Sur quel fondement ?"] },
      { title: "Formule de politesse et signature", goal: "Clore dans les formes", share: 20, prompts: ["Quelle formule selon le destinataire ?"] },
    ],
    method: [
      "Un seul objet par lettre.",
      "Employer « je » pour un particulier, « nous » ou la tournure impersonnelle pour une institution.",
      "Rappeler les références (dossier, courrier antérieur, date).",
      "Formuler la demande de façon explicite et chiffrée si possible.",
      "Reprendre la formule d'appel à l'identique dans la formule de politesse.",
    ],
    connectors: ["Par la présente", "En effet", "Or", "Par conséquent", "En conséquence", "Dans l'attente"],
    phrases: [
      "J'ai l'honneur de solliciter de votre haute bienveillance…",
      "Comme suite à votre courrier du 12 mars 2026, référencé…",
      "Je me permets d'attirer votre attention sur…",
      "Je vous prie d'agréer, Madame la Directrice, l'expression de ma considération distinguée.",
    ],
    checklist: [
      "L'objet est explicite et unique.",
      "Les coordonnées et la date figurent.",
      "Les références du dossier sont rappelées.",
      "La demande est clairement formulée.",
      "La formule de politesse correspond au destinataire.",
      "Les pièces jointes sont listées.",
    ],
    pitfalls: ["Mélanger plusieurs demandes", "Ton familier ou agressif", "Formule de politesse inadaptée", "Absence de date ou de référence"],
    criteria: [
      { label: "Respect des normes formelles", weight: 30 },
      { label: "Clarté de la demande", weight: 30 },
      { label: "Registre et courtoisie", weight: 20 },
      { label: "Correction de la langue", weight: 20 },
    ],
    sample:
      "Objet : Demande de duplicata de relevé de notes — Session juin 2025\n\nMadame la Directrice,\n\nComme suite à mon inscription en Master Didactique du FLE, j'ai l'honneur de solliciter la délivrance d'un duplicata de mon relevé de notes de la session de juin 2025, l'original ayant été égaré lors d'un déménagement.",
  },
  {
    slug: "courriel-professionnel",
    name: "Le courriel professionnel",
    categorySlug: "professionnels",
    summary: "Message électronique bref, structuré et orienté action.",
    definition:
      "Le courriel professionnel transmet une information ou une demande dans un contexte de travail. Son efficacité repose sur un objet informatif, un message scannable (une idée par paragraphe) et une action clairement identifiée avec son échéance.",
    dominantTypes: ["explicatif", "injonctif"],
    register: "courant soutenu",
    length: "80 à 250 mots",
    difficulty: 1,
    plan: [
      { title: "Objet", goal: "Dire le sujet et l'action attendue", share: 10, prompts: ["Objet lisible en liste : action + sujet + échéance ?"] },
      { title: "Contexte", goal: "Deux phrases de rappel", share: 25, prompts: ["Pourquoi ce message, maintenant ?"] },
      { title: "Message principal", goal: "Information ou demande", share: 40, prompts: ["Quelle est la demande précise ?", "Faut-il une liste à puces ?"] },
      { title: "Action et échéance", goal: "Qui fait quoi pour quand", share: 15, prompts: ["Quelle date limite ?"] },
      { title: "Clôture", goal: "Formule brève et signature", share: 10, prompts: ["Formule adaptée au destinataire ?"] },
    ],
    method: [
      "Rédiger l'objet en dernier, une fois le message écrit.",
      "Mettre la demande dans les trois premières lignes.",
      "Une idée par paragraphe, puces pour les listes.",
      "Nommer explicitement le responsable de chaque action.",
      "Relire pour supprimer 20 % des mots.",
    ],
    connectors: ["Pour faire suite à", "Par ailleurs", "Afin de", "Dans ce cadre", "D'ici le", "Je reste à votre disposition"],
    phrases: [
      "Pour faire suite à notre échange de ce matin, …",
      "Pourriez-vous me confirmer… avant vendredi 17 h ?",
      "Vous trouverez ci-joint…",
      "Bien cordialement,",
    ],
    checklist: [
      "L'objet annonce l'action attendue.",
      "La demande apparaît dès le début.",
      "Une échéance est indiquée.",
      "Les pièces jointes sont réellement attachées.",
      "Le ton reste courtois et neutre.",
    ],
    pitfalls: ["Objet vague (« Info »)", "Message fleuve sans paragraphes", "Demande implicite", "Mettre tout le service en copie"],
    criteria: [
      { label: "Clarté de la demande", weight: 35 },
      { label: "Structure et lisibilité", weight: 25 },
      { label: "Ton professionnel", weight: 20 },
      { label: "Concision", weight: 20 },
    ],
    sample:
      "Objet : Validation du planning des soutenances — réponse avant jeudi 12 h\n\nBonjour,\n\nPour faire suite à la réunion du 3 avril, vous trouverez ci-joint le planning des soutenances.\nMerci de me signaler toute indisponibilité avant jeudi 12 h ; sans retour, le planning sera considéré comme validé.",
  },
  {
    slug: "lettre-de-motivation",
    name: "La lettre de motivation",
    categorySlug: "professionnels",
    summary: "Lettre argumentative reliant un profil à un besoin précis.",
    definition:
      "La lettre de motivation démontre l'adéquation entre un parcours et une offre. Elle est argumentative (thèse : « je suis la personne qu'il vous faut ») et explicative (preuves tirées de l'expérience). Le schéma « vous – moi – nous » structure efficacement le propos.",
    dominantTypes: ["argumentatif", "explicatif"],
    register: "soutenu",
    length: "250 à 400 mots",
    difficulty: 3,
    plan: [
      { title: "Accroche ciblée (vous)", goal: "Montrer qu'on connaît l'organisation", share: 20, prompts: ["Quel projet, chiffre ou valeur de l'organisme citer ?"] },
      { title: "Preuves (moi)", goal: "Deux expériences chiffrées en lien direct", share: 40, prompts: ["Quels résultats mesurables ?", "Quelles compétences de l'offre ?"] },
      { title: "Projection (nous)", goal: "Ce que vous apporterez concrètement", share: 25, prompts: ["Quelle contribution dans les six premiers mois ?"] },
      { title: "Disponibilité et politesse", goal: "Proposer un entretien", share: 15, prompts: ["Quelle disponibilité annoncer ?"] },
    ],
    method: [
      "Reprendre trois mots-clés exacts de l'offre.",
      "Transformer chaque qualité affirmée en preuve chiffrée.",
      "Bannir l'ouverture « Je me permets de vous adresser ma candidature ».",
      "Personnaliser : nommer le service, le poste, un projet de l'organisme.",
      "Relire à voix haute : aucune phrase ne doit pouvoir servir pour un autre poste.",
    ],
    connectors: ["C'est pourquoi", "Fort de cette expérience", "Par ailleurs", "Au-delà de", "Dans cette perspective", "Dans l'attente"],
    phrases: [
      "Votre appel à candidatures mentionne… : c'est précisément le cœur de mon travail depuis trois ans.",
      "Au cours de cette mission, j'ai réduit de 30 % le délai de traitement des dossiers.",
      "Je serais heureux de mettre cette expérience au service de…",
      "Je me tiens à votre disposition pour un entretien.",
    ],
    checklist: [
      "Le poste et l'organisme sont nommés.",
      "Chaque compétence est prouvée par un fait.",
      "Des chiffres apparaissent.",
      "Aucun paragraphe n'est transposable à une autre offre.",
      "La lettre tient sur une page.",
      "Orthographe et noms propres vérifiés.",
    ],
    pitfalls: ["Paraphraser le CV", "Parler surtout de ses envies", "Lettre générique", "Formules creuses (« dynamique et motivé »)"],
    criteria: [
      { label: "Adéquation profil / offre", weight: 35 },
      { label: "Force des preuves", weight: 25 },
      { label: "Personnalisation", weight: 20 },
      { label: "Forme et langue", weight: 20 },
    ],
    sample:
      "Votre offre insiste sur l'accompagnement des élèves allophones. C'est le cœur de mon travail depuis trois ans au collège Al Massira, où j'ai conçu un dispositif de tutorat qui a fait passer le taux de réussite de ce public de 54 % à 78 % en deux années.",
  },
  {
    slug: "proces-verbal",
    name: "Le procès-verbal",
    categorySlug: "professionnels",
    summary: "Relation officielle et fidèle d'une séance, à valeur probante.",
    definition:
      "Le procès-verbal consigne officiellement le déroulement d'une séance : présences, ordre du jour, débats résumés, décisions, votes. Il engage juridiquement l'institution ; sa rédaction est impersonnelle, exhaustive sur les décisions et neutre sur les débats.",
    dominantTypes: ["explicatif", "narratif"],
    register: "soutenu",
    length: "400 à 1 200 mots",
    difficulty: 2,
    plan: [
      { title: "En-tête", goal: "Instance, date, heure, lieu, présidence", share: 15, prompts: ["Qui préside ? Qui rédige ?"] },
      { title: "Présences", goal: "Présents, excusés, absents, pouvoirs", share: 10, prompts: ["Le quorum est-il atteint ?"] },
      { title: "Ordre du jour", goal: "Lister les points dans l'ordre", share: 10, prompts: ["Combien de points ?"] },
      { title: "Déroulement par point", goal: "Synthèse des débats et décisions", share: 50, prompts: ["Quelle décision pour chaque point ?", "Quels votes (pour/contre/abstentions) ?"] },
      { title: "Clôture et signatures", goal: "Heure de levée, prochaine séance", share: 15, prompts: ["Date de la prochaine réunion ?"] },
    ],
    method: [
      "Rédiger au passé composé ou au présent, à la troisième personne.",
      "Résumer les positions sans les commenter ni les évaluer.",
      "Faire apparaître chaque décision dans un paragraphe distinct, en gras si possible.",
      "Mentionner les votes chiffrés et les réserves exprimées.",
      "Faire relire et approuver à la séance suivante.",
    ],
    connectors: ["Après avoir", "Sur proposition de", "À l'unanimité", "Après en avoir délibéré", "En conséquence", "L'ordre du jour étant épuisé"],
    phrases: [
      "La séance est ouverte à 14 h 05 sous la présidence de…",
      "Après en avoir délibéré, le conseil adopte la proposition par 12 voix pour, 2 contre et 1 abstention.",
      "M. X rappelle que…",
      "L'ordre du jour étant épuisé, la séance est levée à 16 h 20.",
    ],
    checklist: [
      "Date, heure, lieu et présidence figurent.",
      "La liste des présents et excusés est complète.",
      "Chaque point de l'ordre du jour est traité.",
      "Les décisions et votes sont explicites.",
      "Le texte est rédigé à la troisième personne.",
      "L'heure de clôture est indiquée.",
    ],
    pitfalls: ["Verbatim intégral des échanges", "Commentaires personnels du rédacteur", "Décisions noyées dans le récit", "Oubli des votes et des pouvoirs"],
    criteria: [
      { label: "Exhaustivité des décisions", weight: 35 },
      { label: "Neutralité", weight: 25 },
      { label: "Respect du formalisme", weight: 20 },
      { label: "Clarté", weight: 20 },
    ],
    sample:
      "Point 3 — Budget de la bibliothèque. Après en avoir délibéré, le conseil approuve l'augmentation de 8 % de la dotation documentaire par 11 voix pour et 3 abstentions. Mme Bennani demande que l'acquisition d'ouvrages en amazighe soit priorisée ; la proposition est renvoyée à la commission pédagogique.",
  },
  {
    slug: "compte-rendu-reunion",
    name: "Le compte rendu de réunion",
    categorySlug: "professionnels",
    summary: "Synthèse opérationnelle des échanges et du plan d'action.",
    definition:
      "Moins formel que le procès-verbal, le compte rendu de réunion restitue l'essentiel des échanges et, surtout, les décisions et actions à mener. Il est tourné vers l'action : chaque point se termine par « qui fait quoi pour quand ».",
    dominantTypes: ["explicatif", "injonctif"],
    register: "courant soutenu",
    length: "300 à 800 mots",
    difficulty: 1,
    plan: [
      { title: "Informations générales", goal: "Date, participants, objet", share: 15, prompts: ["Qui était présent ?"] },
      { title: "Points abordés", goal: "Un paragraphe synthétique par sujet", share: 45, prompts: ["Quel était l'enjeu de chaque point ?"] },
      { title: "Décisions", goal: "Lister les arbitrages retenus", share: 20, prompts: ["Qu'a-t-on tranché ?"] },
      { title: "Plan d'action", goal: "Tableau action / responsable / échéance", share: 20, prompts: ["Quelles actions, pour qui, pour quand ?"] },
    ],
    method: [
      "Prendre des notes structurées par point de l'ordre du jour.",
      "Distinguer visuellement informations, décisions et actions.",
      "Nommer un responsable unique par action.",
      "Diffuser dans les 48 heures.",
      "Rester factuel : pas de jugement sur les intervenants.",
    ],
    connectors: ["Concernant", "Il a été rappelé que", "Il a été décidé de", "Par conséquent", "À noter", "Prochaine étape"],
    phrases: [
      "Présents : … / Excusés : …",
      "Il a été décidé de reporter le lancement au 15 mai.",
      "Action : rédiger le cahier des charges — Responsable : S. Alami — Échéance : 30 avril.",
      "Prochaine réunion : mardi 6 mai, 10 h.",
    ],
    checklist: [
      "Les participants sont listés.",
      "Chaque point a une conclusion.",
      "Les décisions sont repérables.",
      "Chaque action a un responsable et une date.",
      "La prochaine échéance est fixée.",
    ],
    pitfalls: ["Transcription chronologique bavarde", "Actions sans responsable", "Diffusion tardive", "Confusion entre discussion et décision"],
    criteria: [
      { label: "Clarté des décisions", weight: 30 },
      { label: "Qualité du plan d'action", weight: 30 },
      { label: "Synthèse des échanges", weight: 20 },
      { label: "Lisibilité", weight: 20 },
    ],
    sample:
      "Concernant la plateforme d'inscription, il a été rappelé que 12 % des dossiers restent incomplets. Il a été décidé d'ajouter un message de relance automatique à J+3. Action : paramétrer la relance — Responsable : service numérique — Échéance : 22 mai.",
  },
  {
    slug: "rapport-activite",
    name: "Le rapport d'activité",
    categorySlug: "professionnels",
    summary: "Bilan structuré d'une période, appuyé sur des indicateurs.",
    definition:
      "Le rapport d'activité présente ce qui a été réalisé sur une période donnée, mesure les écarts par rapport aux objectifs et propose des perspectives. Il combine données chiffrées, analyse et recommandations, et s'ouvre par une synthèse destinée aux décideurs.",
    dominantTypes: ["explicatif", "argumentatif"],
    register: "soutenu",
    length: "1 000 à 3 000 mots",
    difficulty: 3,
    plan: [
      { title: "Synthèse exécutive", goal: "L'essentiel en une page", share: 15, prompts: ["Trois résultats clés ? Trois alertes ?"] },
      { title: "Contexte et objectifs", goal: "Rappeler le cadre et les cibles", share: 15, prompts: ["Quels objectifs avaient été fixés ?"] },
      { title: "Réalisations", goal: "Activités menées, chiffrées", share: 30, prompts: ["Quels indicateurs ? Quelles preuves ?"] },
      { title: "Analyse des écarts", goal: "Expliquer réussites et difficultés", share: 20, prompts: ["Pourquoi cet écart ? Causes internes/externes ?"] },
      { title: "Perspectives et recommandations", goal: "Proposer des actions datées", share: 20, prompts: ["Quelles trois recommandations prioritaires ?"] },
    ],
    method: [
      "Partir des objectifs initiaux : le rapport mesure un écart.",
      "Un indicateur par affirmation : taux, volumes, délais.",
      "Distinguer constat, analyse et recommandation.",
      "Mettre les tableaux et annexes à la fin, les conclusions au début.",
      "Assumer les résultats négatifs en les expliquant.",
    ],
    connectors: ["Au cours de la période", "En comparaison avec", "Cette évolution s'explique par", "En revanche", "Il en résulte que", "Il est recommandé de"],
    phrases: [
      "Au cours de l'exercice 2025, l'activité a progressé de 14 %.",
      "Cet écart s'explique principalement par…",
      "Trois enseignements peuvent être tirés : …",
      "Il est recommandé de redéployer deux postes vers…",
    ],
    checklist: [
      "La synthèse tient sur une page.",
      "Les objectifs initiaux sont rappelés.",
      "Chaque résultat est chiffré.",
      "Les écarts sont analysés.",
      "Les recommandations sont datées et affectées.",
      "Les sources des données sont indiquées.",
    ],
    pitfalls: ["Énumérer des activités sans indicateurs", "Masquer les contre-performances", "Recommandations vagues", "Absence de synthèse initiale"],
    criteria: [
      { label: "Qualité des indicateurs", weight: 30 },
      { label: "Analyse des écarts", weight: 25 },
      { label: "Pertinence des recommandations", weight: 25 },
      { label: "Structure et lisibilité", weight: 20 },
    ],
    sample:
      "Au cours de l'année 2025, le centre a accueilli 1 480 apprenants, soit 14 % de plus qu'en 2024, pour une capacité théorique de 1 300 places. Cette saturation explique l'allongement du délai moyen d'inscription, passé de 6 à 11 jours.",
  },
  {
    slug: "note-de-synthese",
    name: "La note de synthèse",
    categorySlug: "professionnels",
    summary: "Condensé objectif et hiérarchisé d'un dossier pour décider vite.",
    definition:
      "La note de synthèse restitue l'essentiel d'un dossier composé de plusieurs documents, de façon neutre, structurée et autonome : le lecteur doit comprendre sans consulter les sources. Elle est souvent assortie d'une note de propositions lorsqu'une décision est attendue.",
    dominantTypes: ["explicatif"],
    register: "soutenu",
    length: "600 à 1 500 mots (2 à 4 pages)",
    difficulty: 4,
    plan: [
      { title: "Chapô / message essentiel", goal: "Répondre à la question en 5 lignes", share: 15, prompts: ["Quelle est la réponse en une phrase ?"] },
      { title: "Partie I", goal: "Premier axe (état des lieux / constats)", share: 35, prompts: ["Deux sous-parties équilibrées ?"] },
      { title: "Partie II", goal: "Second axe (enjeux / solutions)", share: 35, prompts: ["Quelles options ? Quels risques ?"] },
      { title: "Conclusion ou propositions", goal: "Synthèse ou scénarios d'action", share: 15, prompts: ["Quel scénario recommandé ?"] },
    ],
    method: [
      "Lire le dossier avec une grille : source, date, nature, idée clé.",
      "Construire un plan apparent en deux parties / deux sous-parties.",
      "Référencer chaque information (doc. 3) sans citer longuement.",
      "Rester strictement neutre : aucune opinion personnelle.",
      "Vérifier l'autonomie de la note : compréhensible sans le dossier.",
    ],
    connectors: ["D'une part… d'autre part", "Si… en revanche", "Il ressort du dossier que", "Au-delà de", "En définitive", "Toutefois"],
    phrases: [
      "La présente note a pour objet de…",
      "Il ressort des documents que trois difficultés persistent.",
      "Selon le doc. 4, le délai moyen atteint 11 jours.",
      "Deux scénarios peuvent être envisagés : …",
    ],
    checklist: [
      "Le message essentiel figure en tête.",
      "Le plan est apparent et équilibré.",
      "Toutes les sources importantes sont exploitées.",
      "Aucune opinion personnelle n'apparaît.",
      "La note est autonome.",
      "La longueur imposée est respectée.",
    ],
    pitfalls: ["Résumer les documents l'un après l'autre", "Déséquilibrer les parties", "Oublier un document du dossier", "Introduire des connaissances extérieures non demandées"],
    criteria: [
      { label: "Exploitation complète du dossier", weight: 30 },
      { label: "Hiérarchisation et plan", weight: 30 },
      { label: "Neutralité", weight: 20 },
      { label: "Concision et clarté", weight: 20 },
    ],
    sample:
      "La présente note a pour objet d'éclairer la décision relative à l'extension des horaires de la médiathèque. Il ressort du dossier que la demande est forte (doc. 1 et 3) mais que les contraintes de personnel rendent nécessaire un redéploiement (doc. 5).",
  },
];

export const academicGenres: GenreSeed[] = [
  {
    slug: "dissertation",
    name: "La dissertation",
    categorySlug: "academiques",
    summary: "Réflexion argumentative organisée répondant à une problématique.",
    definition:
      "La dissertation est une démonstration écrite : elle transforme un sujet en problème, puis conduit le lecteur, par étapes argumentées et illustrées, jusqu'à une réponse nuancée. Sa valeur tient à la problématisation, à la rigueur du plan et à la précision des exemples.",
    dominantTypes: ["argumentatif", "explicatif"],
    register: "soutenu",
    length: "1 200 à 2 500 mots",
    difficulty: 4,
    plan: [
      { title: "Introduction", goal: "Amorce, sujet, analyse des termes, problématique, annonce du plan", share: 12, prompts: ["Quelle amorce non banale ?", "Quelle problématique en une question ?"] },
      { title: "Partie I", goal: "Première réponse (thèse), 2 ou 3 sous-parties", share: 26, prompts: ["Quel argument principal ?", "Quels exemples précis ?"] },
      { title: "Partie II", goal: "Limites ou antithèse", share: 26, prompts: ["Quelles objections solides ?"] },
      { title: "Partie III", goal: "Dépassement / synthèse", share: 24, prompts: ["Quel déplacement du problème ?"] },
      { title: "Conclusion", goal: "Bilan + réponse + ouverture", share: 12, prompts: ["La réponse est-elle explicite ?", "Quelle ouverture légitime ?"] },
    ],
    method: [
      "Analyser chaque mot du sujet, y compris les connecteurs et la ponctuation.",
      "Formuler la problématique comme une tension, pas comme une reformulation du sujet.",
      "Construire un plan dialectique (thèse/antithèse/synthèse), analytique ou thématique selon le sujet.",
      "Rédiger chaque paragraphe en AEI : Affirmation – Exemple – Interprétation.",
      "Ménager des transitions explicites entre les parties.",
      "Rédiger l'introduction et la conclusion au brouillon, intégralement.",
    ],
    connectors: ["Tout d'abord", "En outre", "Néanmoins", "Or", "Dès lors", "En définitive"],
    phrases: [
      "Il convient dès lors de se demander si…",
      "Cette position mérite toutefois d'être nuancée.",
      "Ainsi, comme le montre l'exemple de…",
      "Si l'on admet que…, il reste à déterminer…",
    ],
    checklist: [
      "La problématique est formulée sous forme de question.",
      "Le plan est annoncé sans lourdeur.",
      "Chaque sous-partie contient au moins un exemple analysé.",
      "Les transitions relient explicitement les parties.",
      "La conclusion répond à la question posée.",
      "Le « je » est évité (sauf consigne contraire).",
    ],
    pitfalls: ["Plan catalogue sans progression", "Exemples cités mais non analysés", "Paraphrase du sujet en guise de problématique", "Conclusion qui ouvre sans répondre"],
    criteria: [
      { label: "Problématisation", weight: 25 },
      { label: "Construction et progression", weight: 25 },
      { label: "Qualité des exemples et analyses", weight: 30 },
      { label: "Expression et correction", weight: 20 },
    ],
    sample:
      "Si la littérature semble d'abord offrir un refuge hors du monde, elle n'en demeure pas moins l'un des lieux où ce monde se pense. Il convient dès lors de se demander si l'évasion qu'elle procure ne constitue pas, paradoxalement, le détour le plus sûr vers le réel.",
  },
  {
    slug: "commentaire-compose",
    name: "Le commentaire composé",
    categorySlug: "academiques",
    summary: "Analyse organisée d'un texte littéraire, du procédé au sens.",
    definition:
      "Le commentaire composé étudie un extrait en montrant comment l'écriture produit du sens. Il s'organise en axes de lecture (et non ligne à ligne) : chaque axe regroupe des procédés relevés, cités et interprétés, au service d'une interprétation d'ensemble.",
    dominantTypes: ["explicatif", "argumentatif", "descriptif"],
    register: "soutenu",
    length: "1 000 à 2 000 mots",
    difficulty: 4,
    plan: [
      { title: "Introduction", goal: "Présentation, situation, lecture, problématique, axes", share: 12, prompts: ["Quelle caractérisation globale du texte ?", "Quel projet de lecture ?"] },
      { title: "Axe I", goal: "Premier mouvement de lecture", share: 28, prompts: ["Quels procédés ? Quelles citations brèves ?"] },
      { title: "Axe II", goal: "Second axe, complémentaire ou contrastif", share: 28, prompts: ["Quel autre niveau de lecture ?"] },
      { title: "Axe III (facultatif)", goal: "Portée, enjeux, dimension symbolique", share: 20, prompts: ["Quelle portée dépasse l'extrait ?"] },
      { title: "Conclusion", goal: "Bilan interprétatif et élargissement", share: 12, prompts: ["Quel rapprochement avec une autre œuvre ?"] },
    ],
    method: [
      "Lire le texte trois fois : sens global, procédés, structure.",
      "Classer les relevés par effet produit, non par ordre d'apparition.",
      "Suivre la règle du trio : procédé relevé + citation entre guillemets + interprétation.",
      "Éviter la paraphrase : toujours répondre à « quel effet ? ».",
      "Soigner les transitions entre axes.",
    ],
    connectors: ["Ainsi", "De plus", "Or", "En effet", "Par ailleurs", "Dès lors"],
    phrases: [
      "L'extrait se caractérise d'emblée par…",
      "L'allitération en [r] (« … ») traduit la violence de la scène.",
      "Le choix de l'imparfait inscrit la scène dans la durée.",
      "Ce procédé invite le lecteur à…",
    ],
    checklist: [
      "L'introduction situe l'extrait et annonce les axes.",
      "Chaque paragraphe part d'une idée, pas d'un vers.",
      "Les citations sont brèves et entre guillemets.",
      "Chaque procédé est interprété.",
      "La paraphrase est absente.",
      "La conclusion propose un élargissement.",
    ],
    pitfalls: ["Paraphraser le texte", "Relever des procédés sans interprétation", "Étude linéaire déguisée", "Introduction trop longue"],
    criteria: [
      { label: "Pertinence des axes", weight: 30 },
      { label: "Analyse des procédés", weight: 30 },
      { label: "Absence de paraphrase", weight: 20 },
      { label: "Expression", weight: 20 },
    ],
    sample:
      "L'extrait se caractérise d'emblée par un brouillage des repères : la juxtaposition des notations sensorielles (« un bruit, une odeur de suie, quelque chose de froid ») prive le lecteur de toute vue d'ensemble et l'installe, comme le personnage, dans l'incertitude.",
  },
  {
    slug: "synthese-de-documents",
    name: "La synthèse de documents",
    categorySlug: "academiques",
    summary: "Confrontation neutre et organisée de plusieurs sources.",
    definition:
      "La synthèse de documents reformule, confronte et organise les idées d'un corpus sans y ajouter d'opinion. Elle est objective, structurée autour d'un plan problématisé, et traite les documents ensemble — jamais l'un après l'autre.",
    dominantTypes: ["explicatif"],
    register: "soutenu",
    length: "500 à 1 000 mots",
    difficulty: 4,
    plan: [
      { title: "Introduction", goal: "Thème, présentation du corpus, problématique, annonce", share: 15, prompts: ["Quel thème commun ?", "Quelle question traverse le corpus ?"] },
      { title: "Partie I", goal: "Premier axe de confrontation", share: 35, prompts: ["Quels documents convergent ici ?"] },
      { title: "Partie II", goal: "Deuxième axe : nuances, oppositions", share: 35, prompts: ["Où les sources divergent-elles ?"] },
      { title: "Conclusion", goal: "Bilan de la confrontation (sans avis personnel)", share: 15, prompts: ["Quel point reste ouvert dans le corpus ?"] },
    ],
    method: [
      "Construire un tableau de confrontation : idées en lignes, documents en colonnes.",
      "Identifier convergences, divergences et compléments.",
      "Bâtir le plan sur les idées, jamais sur les documents.",
      "Référencer systématiquement : (doc. 1), (doc. 2 et 4).",
      "Reformuler : pas de citations longues, pas de copier-coller.",
    ],
    connectors: ["De même", "À l'inverse", "Tandis que", "En outre", "Si l'on suit", "Il ressort de"],
    phrases: [
      "Le corpus réunit quatre documents consacrés à…",
      "Les documents 1 et 3 s'accordent sur…",
      "Le document 2 nuance cette analyse en rappelant que…",
      "Aucun des auteurs n'aborde la question de…",
    ],
    checklist: [
      "Tous les documents sont exploités.",
      "Le plan est thématique.",
      "Chaque idée est référencée.",
      "Aucune opinion personnelle n'apparaît.",
      "Les reformulations évitent le copier-coller.",
      "La longueur imposée est respectée.",
    ],
    pitfalls: ["Traiter les documents successivement", "Ajouter des connaissances extérieures", "Donner son avis en conclusion", "Oublier un document"],
    criteria: [
      { label: "Confrontation effective des sources", weight: 35 },
      { label: "Organisation du plan", weight: 25 },
      { label: "Objectivité", weight: 20 },
      { label: "Reformulation et langue", weight: 20 },
    ],
    sample:
      "Les documents 1 et 3 s'accordent à voir dans le numérique un facteur d'égalisation de l'accès au savoir. Le document 2 nuance cette analyse en rappelant que l'équipement ne garantit pas l'usage, tandis que le document 4 déplace la question vers la formation des enseignants.",
  },
  {
    slug: "resume-de-texte",
    name: "Le résumé de texte",
    categorySlug: "academiques",
    summary: "Réduction fidèle d'un texte au quart de sa longueur.",
    definition:
      "Le résumé restitue, dans l'ordre et selon le système d'énonciation de l'auteur, l'essentiel d'un texte, avec une contraction normée (souvent au quart). Il n'ajoute rien, ne commente pas et reformule sans recopier.",
    dominantTypes: ["explicatif"],
    register: "soutenu",
    length: "1/4 du texte source",
    difficulty: 3,
    plan: [
      { title: "Repérage", goal: "Thèse, mouvements, articulations", share: 20, prompts: ["Quelle est la thèse ?", "Combien de mouvements ?"] },
      { title: "Réduction", goal: "Une phrase par idée essentielle", share: 50, prompts: ["Quelles idées sont des exemples (à supprimer) ?"] },
      { title: "Rédaction liée", goal: "Rétablir les connecteurs logiques", share: 20, prompts: ["Quels liens logiques reproduire ?"] },
      { title: "Vérification", goal: "Compter les mots, contrôler la fidélité", share: 10, prompts: ["Nombre de mots indiqué ?"] },
    ],
    method: [
      "Supprimer exemples, redites, digressions et illustrations.",
      "Conserver la logique argumentative et le système énonciatif de l'auteur.",
      "Reformuler systématiquement (pas plus de trois mots consécutifs repris).",
      "Respecter la contraction à ±10 %.",
      "Indiquer le nombre de mots à la fin.",
    ],
    connectors: ["Ainsi", "Cependant", "Par conséquent", "Toutefois", "En outre", "Enfin"],
    phrases: [
      "L'auteur montre que…",
      "Il distingue ensuite deux cas…",
      "Il en conclut que…",
      "(248 mots)",
    ],
    checklist: [
      "L'ordre du texte source est respecté.",
      "Le système d'énonciation est conservé.",
      "Aucun exemple n'est conservé.",
      "Aucun commentaire n'est ajouté.",
      "La contraction est respectée.",
      "Le nombre de mots est indiqué.",
    ],
    pitfalls: ["Recopier des segments entiers", "Introduire « l'auteur dit que » à chaque phrase", "Supprimer les connecteurs logiques", "Dépasser le quota de mots"],
    criteria: [
      { label: "Fidélité au texte", weight: 35 },
      { label: "Reformulation", weight: 25 },
      { label: "Respect de la contraction", weight: 20 },
      { label: "Langue", weight: 20 },
    ],
    sample:
      "L'auteur conteste l'idée que la lecture numérique remplacerait la lecture imprimée. Il distingue deux usages — consultation rapide et lecture longue — et montre que seul le premier a été transformé. Il en conclut que la rupture annoncée relève davantage du discours que de la pratique. (48 mots)",
  },
  {
    slug: "article-scientifique",
    name: "L'article scientifique (IMRaD)",
    categorySlug: "academiques",
    summary: "Communication d'une recherche selon la structure IMRaD.",
    definition:
      "L'article scientifique expose une recherche originale selon la structure IMRaD : Introduction, Méthodes, Résultats et Discussion. Il suppose un état de l'art, une question de recherche explicite, une méthodologie reproductible et une discussion honnête des limites.",
    dominantTypes: ["explicatif", "argumentatif"],
    register: "spécialisé",
    length: "4 000 à 8 000 mots",
    difficulty: 5,
    plan: [
      { title: "Résumé et mots-clés", goal: "Condenser objectif, méthode, résultats", share: 8, prompts: ["200 mots maximum : objectif, méthode, résultat, portée ?"] },
      { title: "Introduction", goal: "État de l'art, lacune, question de recherche", share: 20, prompts: ["Quelle lacune dans la littérature ?", "Quelle hypothèse ?"] },
      { title: "Méthodes", goal: "Corpus, protocole, outils, éthique", share: 20, prompts: ["L'étude est-elle reproductible ?"] },
      { title: "Résultats", goal: "Présenter les données sans les interpréter", share: 22, prompts: ["Quels tableaux et figures ?"] },
      { title: "Discussion", goal: "Interpréter, comparer, limiter", share: 22, prompts: ["Quelles limites reconnaître ?", "Quelles perspectives ?"] },
      { title: "Références", goal: "Normer la bibliographie", share: 8, prompts: ["Quelle norme : APA, MLA, Chicago ?"] },
    ],
    method: [
      "Formuler une question de recherche unique et opérationnalisable.",
      "Décrire la méthode assez précisément pour qu'elle soit reproduite.",
      "Séparer strictement résultats (faits) et discussion (interprétation).",
      "Citer selon une norme unique et cohérente.",
      "Reconnaître explicitement les limites de l'étude.",
    ],
    connectors: ["Dans cette perspective", "Conformément à", "Il apparaît que", "Ces résultats suggèrent", "Toutefois", "En conclusion"],
    phrases: [
      "Cette étude vise à déterminer dans quelle mesure…",
      "Le corpus se compose de 240 copies recueillies entre…",
      "Les résultats montrent une corrélation significative (p < 0,05) entre…",
      "Ces résultats doivent être nuancés par la taille réduite de l'échantillon.",
    ],
    checklist: [
      "Le résumé respecte le format demandé.",
      "La question de recherche est explicite.",
      "La méthode est reproductible.",
      "Les résultats ne sont pas interprétés.",
      "Les limites sont discutées.",
      "Les références suivent une norme unique.",
    ],
    pitfalls: ["Confondre résultats et discussion", "État de l'art décoratif", "Sur-interpréter des données limitées", "Bibliographie hétérogène"],
    criteria: [
      { label: "Rigueur méthodologique", weight: 35 },
      { label: "Clarté de la question et des résultats", weight: 25 },
      { label: "Qualité de la discussion", weight: 20 },
      { label: "Normes et bibliographie", weight: 20 },
    ],
    sample:
      "Cette étude vise à déterminer dans quelle mesure l'enseignement explicite des connecteurs logiques améliore la cohésion des productions argumentatives d'élèves de première année universitaire. Le corpus se compose de 240 copies recueillies dans trois établissements entre octobre 2024 et mars 2025.",
  },
  {
    slug: "expose-oral",
    name: "L'exposé oral (support écrit)",
    categorySlug: "academiques",
    summary: "Présentation structurée destinée à être dite devant un auditoire.",
    definition:
      "L'exposé oral se prépare par écrit mais s'écrit pour l'oreille : phrases courtes, annonces explicites, répétitions utiles, supports visuels sobres. Sa réussite dépend de la clarté du fil directeur et de la gestion du temps.",
    dominantTypes: ["explicatif", "argumentatif"],
    register: "courant soutenu",
    length: "10 à 20 minutes (1 200 à 2 400 mots)",
    difficulty: 2,
    plan: [
      { title: "Accroche", goal: "Capter l'attention en 30 secondes", share: 10, prompts: ["Quel chiffre, anecdote ou question pour commencer ?"] },
      { title: "Annonce du fil", goal: "Problématique et plan en trois points", share: 10, prompts: ["Les trois parties tiennent-elles en une phrase chacune ?"] },
      { title: "Développement", goal: "Trois temps équilibrés avec exemples", share: 55, prompts: ["Un exemple marquant par partie ?", "Quelle diapositive associée ?"] },
      { title: "Conclusion", goal: "Récapituler et ouvrir", share: 15, prompts: ["Quel message à retenir ?"] },
      { title: "Questions", goal: "Anticiper trois questions difficiles", share: 10, prompts: ["Quelles objections probables ?"] },
    ],
    method: [
      "Rédiger pour l'oreille : une idée par phrase, peu de subordonnées.",
      "Prévoir des relances explicites : « j'en viens maintenant à… ».",
      "Compter 130 à 150 mots par minute pour calibrer le temps.",
      "Limiter chaque diapositive à six lignes.",
      "Répéter à voix haute et chronométrer au moins deux fois.",
    ],
    connectors: ["Pour commencer", "Premier point", "J'en viens maintenant à", "Retenons que", "Enfin", "Pour conclure"],
    phrases: [
      "Trois chiffres suffisent à poser le problème : …",
      "Je développerai trois points. Premier point : …",
      "Ce qu'il faut retenir, c'est que…",
      "Je suis à votre disposition pour vos questions.",
    ],
    checklist: [
      "Le temps imparti est respecté (test chronométré).",
      "Le plan est annoncé et rappelé.",
      "Chaque partie comporte un exemple concret.",
      "Les diapositives sont lisibles à distance.",
      "Les questions probables sont préparées.",
    ],
    pitfalls: ["Lire ses notes", "Diapositives surchargées", "Plan non annoncé", "Dépassement du temps"],
    criteria: [
      { label: "Structure et fil directeur", weight: 30 },
      { label: "Adaptation à l'oral", weight: 25 },
      { label: "Qualité des supports", weight: 20 },
      { label: "Gestion du temps", weight: 25 },
    ],
    sample:
      "Trois chiffres suffisent à poser le problème : 68 % des élèves déclarent écrire quotidiennement, 12 % se disent à l'aise à l'écrit, 3 % ont déjà réécrit un texte. Je développerai trois points pour expliquer cet écart.",
  },
];
