export type ResourceSeed = {
  slug: string;
  kind: string;
  category: string;
  term: string;
  definition: string;
  items: string[];
  example: string;
};

export const resourceSeeds: ResourceSeed[] = [
  /* ----------------------------- CONNECTEURS ----------------------------- */
  {
    slug: "connecteurs-addition",
    kind: "connecteur",
    category: "Addition / énumération",
    term: "Ajouter un élément",
    definition: "Relient des éléments de même valeur et font progresser l'énumération des arguments ou des faits.",
    items: ["et", "de plus", "en outre", "par ailleurs", "également", "d'une part… d'autre part", "non seulement… mais encore", "qui plus est", "de surcroît", "enfin"],
    example: "Non seulement la réforme coûte cher, mais encore elle arrive trop tard.",
  },
  {
    slug: "connecteurs-cause",
    kind: "connecteur",
    category: "Cause",
    term: "Exprimer la cause",
    definition: "Introduisent la raison, l'origine ou le motif d'un fait.",
    items: ["car", "parce que", "puisque", "comme", "étant donné que", "en effet", "du fait de", "grâce à", "à cause de", "sous l'effet de"],
    example: "Puisque les délais ont été raccourcis, la procédure doit être simplifiée.",
  },
  {
    slug: "connecteurs-consequence",
    kind: "connecteur",
    category: "Conséquence",
    term: "Exprimer la conséquence",
    definition: "Marquent le résultat ou l'effet produit par ce qui précède.",
    items: ["donc", "ainsi", "par conséquent", "c'est pourquoi", "dès lors", "si bien que", "de sorte que", "il en résulte que", "aussi (+ inversion)", "d'où"],
    example: "Le dispositif n'a pas été évalué ; dès lors, aucune généralisation n'est possible.",
  },
  {
    slug: "connecteurs-opposition",
    kind: "connecteur",
    category: "Opposition / concession",
    term: "Opposer et concéder",
    definition: "Marquent le contraste entre deux idées, ou reconnaissent une objection avant de la dépasser.",
    items: ["mais", "cependant", "toutefois", "néanmoins", "en revanche", "alors que", "tandis que", "bien que (+ subj.)", "certes… mais", "il n'en reste pas moins que"],
    example: "Certes, le numérique facilite l'accès aux sources ; il n'en reste pas moins que la lecture longue régresse.",
  },
  {
    slug: "connecteurs-but",
    kind: "connecteur",
    category: "But",
    term: "Exprimer le but",
    definition: "Indiquent l'objectif visé par une action.",
    items: ["pour", "afin de", "afin que (+ subj.)", "dans le but de", "en vue de", "de peur que", "de manière à", "pour que (+ subj.)"],
    example: "Afin que chacun puisse s'inscrire, la plateforme restera ouverte jusqu'au 30 mai.",
  },
  {
    slug: "connecteurs-condition",
    kind: "connecteur",
    category: "Condition / hypothèse",
    term: "Poser une condition",
    definition: "Subordonnent la réalisation d'un fait à une circonstance.",
    items: ["si", "à condition que (+ subj.)", "pourvu que", "au cas où (+ cond.)", "à moins que", "dans l'hypothèse où", "sauf si", "en cas de"],
    example: "Au cas où le quorum ne serait pas atteint, la séance serait reportée.",
  },
  {
    slug: "connecteurs-temps",
    kind: "connecteur",
    category: "Temps / chronologie",
    term: "Situer dans le temps",
    definition: "Organisent la succession des événements dans un récit ou une procédure.",
    items: ["d'abord", "ensuite", "puis", "alors", "soudain", "aussitôt", "pendant que", "après avoir", "dès que", "enfin"],
    example: "Dès que le signal retentit, les candidats cessent d'écrire.",
  },
  {
    slug: "connecteurs-illustration",
    kind: "connecteur",
    category: "Illustration / exemple",
    term: "Illustrer",
    definition: "Introduisent un exemple, une preuve ou une référence concrète.",
    items: ["par exemple", "ainsi", "notamment", "en particulier", "comme le montre", "à l'image de", "c'est le cas de", "tel que", "en témoigne"],
    example: "Ainsi, comme le montre l'exemple du Horla, le fantastique naît du doute.",
  },
  {
    slug: "connecteurs-reformulation",
    kind: "connecteur",
    category: "Reformulation / précision",
    term: "Reformuler",
    definition: "Reprennent une idée pour la clarifier ou la préciser.",
    items: ["c'est-à-dire", "autrement dit", "en d'autres termes", "plus précisément", "à savoir", "soit", "en clair", "pour le dire autrement"],
    example: "Le texte est injonctif, autrement dit il cherche à faire agir son destinataire.",
  },
  {
    slug: "connecteurs-conclusion",
    kind: "connecteur",
    category: "Conclusion / bilan",
    term: "Conclure",
    definition: "Signalent la synthèse ou la fin de la démonstration.",
    items: ["en conclusion", "en définitive", "finalement", "au total", "en somme", "pour conclure", "tout bien considéré", "il ressort de ce qui précède que"],
    example: "En définitive, la typologie ne s'oppose pas aux genres : elle les traverse.",
  },
  {
    slug: "connecteurs-comparaison",
    kind: "connecteur",
    category: "Comparaison",
    term: "Comparer",
    definition: "Rapprochent deux éléments pour en marquer la ressemblance ou l'écart.",
    items: ["comme", "de même que", "ainsi que", "plus… que", "moins… que", "à l'instar de", "contrairement à", "par rapport à", "au même titre que"],
    example: "À l'instar de la dissertation, la note de synthèse exige un plan apparent.",
  },
  {
    slug: "connecteurs-classement",
    kind: "connecteur",
    category: "Classement / hiérarchie",
    term: "Hiérarchiser",
    definition: "Ordonnent les arguments selon leur importance.",
    items: ["en premier lieu", "en second lieu", "avant tout", "surtout", "principalement", "accessoirement", "par-dessus tout", "en dernier lieu"],
    example: "Avant tout, il s'agit de définir les termes ; accessoirement, d'en discuter les usages.",
  },

  /* --------------------------- FIGURES DE STYLE -------------------------- */
  {
    slug: "figures-analogie",
    kind: "figure",
    category: "Figures d'analogie",
    term: "Rapprocher deux réalités",
    definition: "Créent un lien d'image entre deux éléments pour rendre sensible une idée abstraite.",
    items: [
      "Comparaison : rapprochement explicite avec un outil (comme, tel, semblable à).",
      "Métaphore : rapprochement implicite, sans outil (« la nuit de son regard »).",
      "Personnification : attribution de traits humains à une chose.",
      "Allégorie : représentation concrète d'une idée abstraite (la Justice aux yeux bandés).",
      "Métaphore filée : image poursuivie sur plusieurs phrases.",
    ],
    example: "La ville dormait d'un sommeil de pierre : les volets clos lui faisaient des paupières.",
  },
  {
    slug: "figures-insistance",
    kind: "figure",
    category: "Figures d'insistance",
    term: "Amplifier",
    definition: "Renforcent l'intensité du propos par la répétition ou l'exagération.",
    items: [
      "Anaphore : répétition d'un mot en début de propositions.",
      "Gradation : progression croissante ou décroissante.",
      "Hyperbole : exagération volontaire.",
      "Accumulation : juxtaposition de termes de même nature.",
      "Répétition et pléonasme expressif.",
    ],
    example: "Rien ne bouge, rien n'appelle, rien ne répond.",
  },
  {
    slug: "figures-opposition",
    kind: "figure",
    category: "Figures d'opposition",
    term: "Opposer",
    definition: "Mettent en relief par le contraste.",
    items: [
      "Antithèse : opposition de deux termes dans une même phrase.",
      "Oxymore : alliance de deux mots contradictoires (« obscure clarté »).",
      "Chiasme : construction croisée AB / BA.",
      "Paradoxe : énoncé contraire à l'opinion commune.",
      "Antiphrase : dire le contraire de ce que l'on pense (ironie).",
    ],
    example: "On écrit peu parce qu'on lit peu, et l'on lit peu parce qu'on écrit peu.",
  },
  {
    slug: "figures-attenuation",
    kind: "figure",
    category: "Figures d'atténuation",
    term: "Atténuer",
    definition: "Adoucissent ou voilent l'expression.",
    items: [
      "Euphémisme : adoucir une réalité brutale (« il nous a quittés »).",
      "Litote : dire moins pour suggérer plus (« ce n'est pas mauvais »).",
      "Périphrase : remplacer un mot par une expression (« la capitale économique »).",
      "Prétérition : annoncer qu'on ne dira pas ce qu'on dit.",
    ],
    example: "Je ne vous cacherai pas que ce rapport n'est pas dénué de lacunes.",
  },
  {
    slug: "figures-construction",
    kind: "figure",
    category: "Figures de construction",
    term: "Jouer sur la syntaxe",
    definition: "Modifient l'ordre ou la forme de la phrase pour produire un effet.",
    items: [
      "Ellipse : suppression d'un élément attendu.",
      "Asyndète : suppression des connecteurs.",
      "Parallélisme : reprise d'une même structure syntaxique.",
      "Inversion : déplacement du sujet ou du complément.",
      "Anacoluthe : rupture volontaire de construction.",
    ],
    example: "Il parlait ; elle écoutait ; la nuit tombait.",
  },

  /* ------------------------------ FORMULES ------------------------------- */
  {
    slug: "formules-appel",
    kind: "formule",
    category: "Correspondance : formules d'appel",
    term: "Ouvrir une lettre",
    definition: "Le choix dépend du statut du destinataire ; la formule d'appel doit être reprise telle quelle dans la formule finale.",
    items: [
      "Madame, Monsieur, — destinataire inconnu",
      "Madame la Directrice, — fonction connue",
      "Monsieur le Doyen,",
      "Monsieur le Professeur,",
      "Cher collègue, — relation professionnelle établie",
      "Bonjour, — courriel courant",
    ],
    example: "Madame la Directrice, … Je vous prie d'agréer, Madame la Directrice, l'expression de ma haute considération.",
  },
  {
    slug: "formules-politesse",
    kind: "formule",
    category: "Correspondance : formules de politesse",
    term: "Clore une lettre",
    definition: "Formules finales classées du plus déférent au plus courant.",
    items: [
      "Je vous prie d'agréer, Madame, l'expression de ma très haute considération. (autorité)",
      "Veuillez agréer, Monsieur, l'expression de mes salutations distinguées. (administratif)",
      "Je vous prie de croire, Madame, en l'assurance de ma considération distinguée.",
      "Dans l'attente de votre réponse, je vous prie d'agréer…",
      "Bien cordialement, / Cordialement, (courriel professionnel)",
      "Respectueusement, (hiérarchie)",
    ],
    example: "Dans l'attente d'une réponse favorable, je vous prie d'agréer, Monsieur le Directeur, l'expression de ma considération distinguée.",
  },
  {
    slug: "formules-demande",
    kind: "formule",
    category: "Correspondance : formuler une demande",
    term: "Demander",
    definition: "Tournures administratives consacrées pour exprimer une requête.",
    items: [
      "J'ai l'honneur de solliciter…",
      "Je me permets de vous demander…",
      "Je sollicite de votre bienveillance…",
      "Pourriez-vous avoir l'obligeance de…",
      "Je vous saurais gré de bien vouloir…",
      "Il vous est demandé de…",
    ],
    example: "Je vous saurais gré de bien vouloir me faire parvenir une attestation de scolarité.",
  },

  /* ------------------------ VERBES INTRODUCTEURS ------------------------- */
  {
    slug: "verbes-opinion",
    kind: "verbe",
    category: "Verbes de prise de position",
    term: "Introduire une thèse",
    definition: "Nuancent le degré d'adhésion de l'énonciateur à l'idée rapportée.",
    items: ["affirmer", "soutenir", "prétendre", "estimer", "considérer que", "contester", "réfuter", "concéder", "nuancer", "objecter"],
    example: "L'auteur ne se contente pas d'affirmer : il concède d'abord, puis réfute.",
  },
  {
    slug: "verbes-analyse",
    kind: "verbe",
    category: "Verbes d'analyse (commentaire)",
    term: "Analyser un procédé",
    definition: "Permettent de relier un fait de langue à un effet de sens.",
    items: ["traduire", "souligner", "mettre en relief", "suggérer", "révéler", "instaurer", "rendre compte de", "témoigner de", "figurer", "amplifier"],
    example: "L'anaphore souligne l'obstination du personnage et instaure un rythme incantatoire.",
  },
  {
    slug: "verbes-parole",
    kind: "verbe",
    category: "Verbes de parole (récit)",
    term: "Introduire un dialogue",
    definition: "Remplacent « dire » et caractérisent l'intention du locuteur.",
    items: ["murmurer", "souffler", "rétorquer", "objecter", "s'exclamer", "balbutier", "ironiser", "trancher", "confier", "insister"],
    example: "« Pas question », trancha-t-elle sans lever les yeux.",
  },

  /* ------------------------------- LEXIQUE ------------------------------- */
  {
    slug: "lexique-emotions",
    kind: "lexique",
    category: "Champ lexical des émotions",
    term: "Dire l'émotion avec précision",
    definition: "Nuancer plutôt qu'amplifier : préférer le mot juste à l'intensif.",
    items: ["appréhension", "effroi", "stupeur", "désarroi", "soulagement", "allégresse", "mélancolie", "amertume", "exaltation", "lassitude"],
    example: "Ce n'était pas de la peur : une appréhension sourde, qui ne disait pas son nom.",
  },
  {
    slug: "lexique-jugement",
    kind: "lexique",
    category: "Vocabulaire évaluatif",
    term: "Juger une œuvre ou une idée",
    definition: "Termes mélioratifs et péjoratifs pour la critique et l'argumentation.",
    items: ["magistral", "convaincant", "subtil", "rigoureux", "stimulant", "convenu", "laborieux", "spécieux", "superficiel", "contestable"],
    example: "Une démonstration rigoureuse, mais une conclusion un peu convenue.",
  },
  {
    slug: "lexique-academique",
    kind: "lexique",
    category: "Lexique de la démonstration",
    term: "Structurer une pensée",
    definition: "Termes charnières du discours universitaire.",
    items: ["problématique", "hypothèse", "corpus", "postulat", "corollaire", "paradigme", "enjeu", "limite", "portée", "critère"],
    example: "Le corpus retenu permet de tester l'hypothèse sans prétendre à la généralisation.",
  },
  {
    slug: "lexique-sensoriel",
    kind: "lexique",
    category: "Champ lexical des sensations",
    term: "Décrire par les sens",
    definition: "Vocabulaire pour une description incarnée.",
    items: ["crissement", "bruissement", "âcre", "moite", "rugueux", "satiné", "blafard", "mordoré", "poisseux", "diaphane"],
    example: "Une lumière blafarde, un air moite, le crissement du gravier : la scène tenait en trois sensations.",
  },
];
